# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: samples.tsv
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g. lanes, or resequencing of the same biological
# sample).
units: units.tsv

# the sequencing adapter (TruSeq)
adapter: AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC

ref:
  # the STAR index
  index: "/mnt/data1/John/DATA_Common/Genomes/GRCm38.p5_M15/"
  # gtf file with transcripts
  annotation: "/mnt/data1/John/DATA_Common/GENCODE/M15_GRCm38.p5/gencode.vM15.annotation.gtf"

pca:
  labels:
    # columns of sample sheet to use for PCA
    - condition

diffexp:
  # contrasts for the deseq2 results method
  contrasts:
    Tcf1KO-vs-WT:
        # put the condition for the left of the volcano plot first
      - Tcf1KO
      - WT
  label:
    - "TCF1KO vs WT"

params:
  star: "--genomeLoad LoadAndKeep --limitBAMsortRAM 10000000000 --alignMatesGapMax 2000 --alignSJDBoverhangMin 9999 --alignSJoverhangMin 9999 --alignIntronMax 1 --outFilterMultimapNmax 1 --outFilterScoreMinOverLread 0 --outFilterMatchNminOverLread 0 --seedSearchStartLmax 30 --alignEndsType Local --outReadsUnmapped Fastx "
  cutadapt-se: ""
  cutadapt-pe: ""
  macs2: "mm"
  blacklist: "/mnt/data1/John/DATA_Common/blacklist/mm10.blacklist.bed"
  homer: "/mnt/data1/John/bin/pyenv/versions/anaconda3-5.0.1/pkgs/homer-4.9.1-pl5.22.0_5/share/homer-4.9.1-5/data/genomes/mm10"
  genome: "/mnt/data1/John/DATA_Common/chrom.sizes/mm10.chrom.sizes"
